language: generic
#services:
#  - docker

#before_install:
#  - sudo apt update -q
#install:

#before_script:
#script:

stages:
  - build
  - static analysis
  - test

jobs:
  include:
    - stage: build
      name: 'Test compilation/build success'
      script: skip
    - stage: static analysis
      name: 'Static analyzer tools'
      script: skip
    - stage: test
      name: 'Unit tests'
      script: skip


#after_success:
#after_failure:

#before_deploy:
#deploy:
#  on:
#    branch: main
#after_deploy:

#after_script: