/**
 * This file houses our Action Creator type constants.
 */
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const GET_PUBLICATION_BY_ID = 'GET_PUBLICATION_BY_ID';
export const GET_PUBLICATIONS_BY_TEAM_ID = 'GET_PUBLICATIONS_BY_TEAM_ID';

export const ADD_USER_DATA = 'ADD_USER_DATA';
// export const CREATE_PUBLICATION = 'CREATE_PUBLICATION'
// export const UPDATE_PUBLICATION = 'UPDATE_PUBLICATION'
// export const DELETE_PUBLICATION = 'DELETE_PUBLICATION'

export const FETCH_TEAM_INFO = 'FETCH_TEAM_INFO';
export const LINK_TEAM_TWITTER = 'LINK_TEAM_TWITTER';
export const UNLINK_TEAM_TWITTER = 'UNLINK_TEAM_TWITTER';