name: Researchify CI

on: [push, pull_request, workflow_dispatch]

jobs:
  static_analysis:
    name: Static Analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
        working-directory: ./api
      - run: npm install
        working-directory: ./client
      - name: Run ESLint on Node API
        run: npm run lint
        working-directory: ./api
      - name: Run ESLint on React Client
        run: npm run lint
        working-directory: ./client
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
        working-directory: ./api
      - run: npm install
        working-directory: ./client
      - name: Run Tests on Node API
        run: npm run test
        working-directory: ./api
      - name: Run Tests on React Client
        run: npm run testcov
        working-directory: ./client
  publish:
    name: Publish Images to Docker Hub
    needs:
      - static_analysis
      - test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push API Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ak1738/reasearchify-api:latest
      - name: Push Client Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ak1738/reasearchify-client:latest
      - name: Push NGINX Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ak1738/reasearchify-nginx:latest