name: Researchify CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  static_analysis:
    name: Static Analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
        working-directory: ./api
      - run: npm install
        working-directory: ./client
      - name: Run ESLint on Node API
        run: npm run lint
        working-directory: ./api
      - name: Run ESLint on React Client
        run: npm run lint
        working-directory: ./client
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
        working-directory: ./api
      - run: npm install
        working-directory: ./client
      - name: Run Tests on Node API
        run: npm run test
        working-directory: ./api
      - name: Run Tests on React Client
        run: npm run testcov
        working-directory: ./client
#   trigger-deploy-doc:
#     name: Generate and deploy docs for researchify.github.io
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.DOCS_WORKFLOW_PAT }}
#           repository: Researchify/researchify.github.io
#           event-type: trigger-deploy
  publish:
    name: Publish Images to Docker Hub
    needs:
      - static_analysis
      - test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push API Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ak1738/researchify-api:latest
      - name: Push Client Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ak1738/researchify-client:latest
      - name: Push NGINX Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ak1738/researchify-nginx:latest
      - name: Push Scholly Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./scholly
          file: ./scholly/Dockerfile
          push: true
          tags: ak1738/researchify-scholly:latest
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs:
      - static_analysis
      - test
      - publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*' '**/node_modules/*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "researchify"
          environment_name: "Researchify-env"
          version_label: 1
          region: "ap-southeast-2"
          deployment_package: deploy.zip
          use_existing_version_if_available: true
