name: Slack Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: pr-notifs
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://img1.pnghut.com/0/17/24/kU8sKLLhx9/logo-robotics-technology-autonomous-robot-text.jpg
        SLACK_USERNAME: Researchify PR Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
