name: Slack Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: pr-notifs
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://www.shareicon.net/data/128x128/2016/08/23/819191_magnifying-glass_512x512.png
        SLACK_USERNAME: Researchify PR Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
